source 'https://rubygems.org'

gem 'bosh_common'
gem 'bosh_cpi'
gem 'excon'
gem 'fog-openstack', git: 'https://github.com/cloudsome-io/fog-openstack.git', branch: "quickfix_multiple_catalog_endpoint"
gem 'httpclient'
gem 'membrane'
gem 'netaddr'

group :development, :test do
  gem 'pry-byebug'
  gem 'rb-readline'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rubocop'
  gem 'timecop'
  gem 'webmock'
  gem 'bosh-template'
end
